//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_background_final_H
#define METASPRITE_background_final_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define background_final_TILE_ORIGIN 0
#define background_final_TILE_W 8
#define background_final_TILE_H 8
#define background_final_WIDTH 160
#define background_final_HEIGHT 144
#define background_final_TILE_COUNT 216
#define background_final_PALETTE_COUNT 1
#define background_final_COLORS_PER_PALETTE 4
#define background_final_TOTAL_COLORS 4
#define background_final_MAP_ATTRIBUTES 0
extern const unsigned char background_final_map[360];
#define background_final_map_attributes background_final_map

BANKREF_EXTERN(background_final)

extern const palette_color_t background_final_palettes[4];
extern const uint8_t background_final_tiles[3456];

#endif
