//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_background_finalle2_H
#define METASPRITE_background_finalle2_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define background_finalle2_TILE_ORIGIN 0
#define background_finalle2_TILE_W 8
#define background_finalle2_TILE_H 8
#define background_finalle2_WIDTH 160
#define background_finalle2_HEIGHT 144
#define background_finalle2_TILE_COUNT 216
#define background_finalle2_PALETTE_COUNT 1
#define background_finalle2_COLORS_PER_PALETTE 4
#define background_finalle2_TOTAL_COLORS 4
#define background_finalle2_MAP_ATTRIBUTES 0
extern const unsigned char background_finalle2_map[360];
#define background_finalle2_map_attributes background_finalle2_map

BANKREF_EXTERN(background_finalle2)

extern const palette_color_t background_finalle2_palettes[4];
extern const uint8_t background_finalle2_tiles[3456];

#endif
