//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_Jester_2_H
#define METASPRITE_Jester_2_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define Jester_2_TILE_ORIGIN 0
#define Jester_2_TILE_W 8
#define Jester_2_TILE_H 16
#define Jester_2_WIDTH 32
#define Jester_2_HEIGHT 48
#define Jester_2_TILE_COUNT 18
#define Jester_2_PALETTE_COUNT 1
#define Jester_2_COLORS_PER_PALETTE 4
#define Jester_2_TOTAL_COLORS 4
#define Jester_2_PIVOT_X 16
#define Jester_2_PIVOT_Y 24
#define Jester_2_PIVOT_W 32
#define Jester_2_PIVOT_H 48
extern const metasprite_t* const Jester_2_metasprites[1];

BANKREF_EXTERN(Jester_2)

extern const palette_color_t Jester_2_palettes[4];
extern const uint8_t Jester_2_tiles[288];

#endif
