//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_Poodle2_H
#define METASPRITE_Poodle2_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define Poodle2_TILE_ORIGIN 0
#define Poodle2_TILE_W 8
#define Poodle2_TILE_H 8
#define Poodle2_WIDTH 40
#define Poodle2_HEIGHT 40
#define Poodle2_TILE_COUNT 19
#define Poodle2_PALETTE_COUNT 1
#define Poodle2_COLORS_PER_PALETTE 4
#define Poodle2_TOTAL_COLORS 4
#define Poodle2_MAP_ATTRIBUTES 0
extern const unsigned char Poodle2_map[25];
#define Poodle2_map_attributes Poodle2_map

BANKREF_EXTERN(Poodle2)

extern const palette_color_t Poodle2_palettes[4];
extern const uint8_t Poodle2_tiles[304];

#endif
