//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_Sprite_0002_H
#define METASPRITE_Sprite_0002_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define Sprite_0002_TILE_ORIGIN 0
#define Sprite_0002_TILE_W 8
#define Sprite_0002_TILE_H 8
#define Sprite_0002_WIDTH 32
#define Sprite_0002_HEIGHT 32
#define Sprite_0002_TILE_COUNT 9
#define Sprite_0002_PALETTE_COUNT 1
#define Sprite_0002_COLORS_PER_PALETTE 4
#define Sprite_0002_TOTAL_COLORS 4
#define Sprite_0002_MAP_ATTRIBUTES 0
extern const unsigned char Sprite_0002_map[16];
#define Sprite_0002_map_attributes Sprite_0002_map

BANKREF_EXTERN(Sprite_0002)

extern const palette_color_t Sprite_0002_palettes[4];
extern const uint8_t Sprite_0002_tiles[144];

#endif
