//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_test2_H
#define METASPRITE_test2_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define test2_TILE_ORIGIN 0
#define test2_TILE_W 8
#define test2_TILE_H 8
#define test2_WIDTH 32
#define test2_HEIGHT 32
#define test2_TILE_COUNT 16
#define test2_PALETTE_COUNT 1
#define test2_COLORS_PER_PALETTE 4
#define test2_TOTAL_COLORS 4
#define test2_MAP_ATTRIBUTES 0
extern const unsigned char test2_map[16];
#define test2_map_attributes test2_map

BANKREF_EXTERN(test2)

extern const palette_color_t test2_palettes[4];
extern const uint8_t test2_tiles[256];

#endif
