/*

 TEST.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char Test[] =
{


 // 00 -white
 // 01 -light gray
 // 10 -dark gray
 // 11 -black
 // 1010 1010 lsb -> 2 Hex Zahlen repräsentieren eine Reihe aus 8 Pixeln
 // 1010 1010 msg -> 1 1 = schwarz
 
  0xAA,0xAA,
  0x00,0x55, // 0000 0000 lsb || 0101 0101 msg
  0xFF,0x00, // 1111 1111 lsb || 0000 0000 msg
  0x00,0x00, // 0000 0000 lsb || 0000 0000 msg
  0xA2,0x8A, // 1010 0010 lsb || 1000 1010 msg
  0x00,0x00,
  0x00,0x00,
  0x00,0x00
};

/* End of TEST.C */
